# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  hangman_config = debug

else ifeq ($(config),release)
  hangman_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := hangman

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

hangman:
ifneq (,$(hangman_config))
	@echo "==== Building hangman ($(hangman_config)) ===="
	@${MAKE} --no-print-directory -C hangman -f Makefile config=$(hangman_config)
endif

clean:
	@${MAKE} --no-print-directory -C hangman -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   hangman"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"